name: quiz_ai
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Version settings
version: 1.0.0+1

# SDK environment
environment:
  sdk: ^3.5.0

# Dependencies for the Flutter app
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.1                # Updated to the latest version
  flutter_facebook_auth: ^7.1.1          # Updated to the latest version

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1        # Updated to the latest version

# Flutter launcher icons configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/Quizai_logo.png"  # Path to the new PNG app icon
  adaptive_icon_background: "#FFFFFF"        # Background color for Android adaptive icons
  adaptive_icon_foreground: "assets/icon/Quizai_logo.png"  # Foreground image for adaptive icon

# Flutter-specific configuration
flutter:
  uses-material-design: true

  # Assets used in the app
  assets:
    - assets/icon/Quizai_logo.png         # Use the new PNG icon instead of JPG

  # Fonts can be added here if needed
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
