name: quiz_ai
description: A new Flutter project.

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Version settings
version: 1.0.0+1

# SDK environment
environment:
  sdk: '>=2.17.0 <4.0.0'

# Dependencies for the Flutter app
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  font_awesome_flutter: ^10.1.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  shelf: ^1.3.0
  shelf_router: ^1.1.0
  http: ^1.2.2
  url_launcher: ^6.3.0
  html_unescape: ^2.0.0
  cloud_firestore: ^5.4.4
  sign_in_with_apple: ^6.1.3
  excel: ^4.0.6
  pdf: ^3.11.1
  pdf_render: ^1.4.12
  image: ^4.2.0
  flutter_tesseract_ocr: ^0.4.26
  firebase_storage: ^12.3.2




# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1


# Flutter launcher icons configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/Quizai_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/Quizai_logo.png"

# Flutter-specific configuration
flutter:
  uses-material-design: true

  # Assets used in the app
  assets:
    - assets/icon/Quizai_logo.png
    - assets/home.png
    - assets/dashboard.png
    - assets/python.png
    - assets/c++.png
    - assets/java.png
    - assets/dart.png
    - assets/javascript.png
    - assets/google.png
    - assets/facebook.png
    - assets/quiz.png




  # Fonts can be added here if needed
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf