// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnnYADXcN2lGrO1et5lO3bXxNTNT6laZw',
    appId: '1:384297989105:web:c66beaaf82d05f8b664a50',
    messagingSenderId: '384297989105',
    projectId: 'quizai-93293',
    authDomain: 'quizai-93293.firebaseapp.com',
    storageBucket: 'quizai-93293.appspot.com',
    measurementId: 'G-MBL8FRY9J9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo3AESbF4ORT-oOs38q8mWG3shcwDGa1Q',
    appId: '1:384297989105:android:89432d6695e8165c664a50',
    messagingSenderId: '384297989105',
    projectId: 'quizai-93293',
    storageBucket: 'quizai-93293.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQUKbhc_6hgYVf5qpGGd1KiHVPG_LtOGI',
    appId: '1:384297989105:ios:1dcd5912b62dc7e2664a50',
    messagingSenderId: '384297989105',
    projectId: 'quizai-93293',
    storageBucket: 'quizai-93293.appspot.com',
    androidClientId: '384297989105-j3jn91dvc963qcd3juuc7gg5v49hhgdv.apps.googleusercontent.com',
    iosClientId: '384297989105-rqc507ap5q53qlgfkv23sc42ia6ku1b4.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQUKbhc_6hgYVf5qpGGd1KiHVPG_LtOGI',
    appId: '1:384297989105:ios:1dcd5912b62dc7e2664a50',
    messagingSenderId: '384297989105',
    projectId: 'quizai-93293',
    storageBucket: 'quizai-93293.appspot.com',
    androidClientId: '384297989105-j3jn91dvc963qcd3juuc7gg5v49hhgdv.apps.googleusercontent.com',
    iosClientId: '384297989105-rqc507ap5q53qlgfkv23sc42ia6ku1b4.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnnYADXcN2lGrO1et5lO3bXxNTNT6laZw',
    appId: '1:384297989105:web:09ba682f49facda4664a50',
    messagingSenderId: '384297989105',
    projectId: 'quizai-93293',
    authDomain: 'quizai-93293.firebaseapp.com',
    storageBucket: 'quizai-93293.appspot.com',
    measurementId: 'G-6PY1JKV74D',
  );
}
